language: csharp
mono: none
dotnet: 1.0.0-preview2-003121

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
    - os: osx # OSX 10.11
      ##osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121

solution: ./src/exceltk.sln
script:
  - ./src/test.sh